
---
- name: Create and Deploy Docker Container
  hosts: all
  become: yes
  tasks:
    - name: Create Dockerfile
      copy:
        dest: /opt/homelab/Dockerfile
        content: |
          FROM python:3.10-alpine

          COPY requirements.txt /tmp

          RUN pip install -r /tmp/requirements.txt

          COPY ./src /src

          CMD python /src/app.py
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Build Docker image
      docker_image:
        name: python-app
        tag: v1
        source: build
        build:
          path: /opt/homelab
        state: present

    - name: Run Docker container
      shell: docker run -d --name python-app-flask --restart always -p 8080:5000 python-app:v1
      
